server:
  servlet:
    encoding:
      force: true
    context-path: /
  port: 8080
  tomcat:
    uri-encoding: utf-8
    accept-count: 1000


logging:
  level:
    org.springframework: warn
    com.wrxiang: info


swagger:
  enabled: true